DELETE FROM ebegu_vorlage
WHERE NAME = 'VORLAGE_FREIGABEQUITTUNG_JUGENDAMT';

DELETE FROM ebegu_vorlage_aud
WHERE NAME = 'VORLAGE_FREIGABEQUITTUNG_JUGENDAMT';

DELETE FROM ebegu_vorlage
WHERE NAME = 'VORLAGE_FREIGABEQUITTUNG_SCHULAMT';

DELETE FROM ebegu_vorlage_aud
WHERE NAME = 'VORLAGE_FREIGABEQUITTUNG_SCHULAMT';