UPDATE application_property
SET name = 'ANZAHL_TAGE_BIS_WARNUNG_FREIGABE'
WHERE name = 'ANZAHL_MONATE_BIS_WARNUNG_FREIGABE';
UPDATE application_property
SET name = 'ANZAHL_TAGE_BIS_WARNUNG_QUITTUNG'
WHERE name = 'ANZAHL_MONATE_BIS_WARNUNG_QUITTUNG';
UPDATE application_property
SET name = 'ANZAHL_TAGE_BIS_LOESCHUNG_NACH_WARNUNG_FREIGABE'
WHERE name = 'ANZAHL_MONATE_BIS_LOESCHUNG_NACH_WARNUNG_FREIGABE';
UPDATE application_property
SET name = 'ANZAHL_TAGE_BIS_LOESCHUNG_NACH_WARNUNG_QUITTUNG'
WHERE name = 'ANZAHL_MONATE_BIS_LOESCHUNG_NACH_WARNUNG_QUITTUNG';

UPDATE application_property_aud
SET name = 'ANZAHL_TAGE_BIS_WARNUNG_FREIGABE'
WHERE name = 'ANZAHL_MONATE_BIS_WARNUNG_FREIGABE';
UPDATE application_property_aud
SET name = 'ANZAHL_TAGE_BIS_WARNUNG_QUITTUNG'
WHERE name = 'ANZAHL_MONATE_BIS_WARNUNG_QUITTUNG';
UPDATE application_property_aud
SET name = 'ANZAHL_TAGE_BIS_LOESCHUNG_NACH_WARNUNG_FREIGABE'
WHERE name = 'ANZAHL_MONATE_BIS_LOESCHUNG_NACH_WARNUNG_FREIGABE';
UPDATE application_property_aud
SET name = 'ANZAHL_TAGE_BIS_LOESCHUNG_NACH_WARNUNG_QUITTUNG'
WHERE name = 'ANZAHL_MONATE_BIS_LOESCHUNG_NACH_WARNUNG_QUITTUNG';

UPDATE application_property
SET value = '60'
WHERE name = 'ANZAHL_TAGE_BIS_WARNUNG_FREIGABE';
UPDATE application_property
SET value = '15'
WHERE name = 'ANZAHL_TAGE_BIS_WARNUNG_QUITTUNG';
UPDATE application_property
SET value = '60'
WHERE name = 'ANZAHL_TAGE_BIS_LOESCHUNG_NACH_WARNUNG_FREIGABE';
UPDATE application_property
SET value = '90'
WHERE name = 'ANZAHL_TAGE_BIS_LOESCHUNG_NACH_WARNUNG_QUITTUNG';

ALTER TABLE gesuch
	DROP COLUMN gewarnt_nicht_freigegeben;
ALTER TABLE gesuch
	DROP COLUMN gewarnt_fehlende_quittung;

ALTER TABLE gesuch_aud
	DROP COLUMN gewarnt_nicht_freigegeben;
ALTER TABLE gesuch_aud
	DROP COLUMN gewarnt_fehlende_quittung;

ALTER TABLE gesuch
	ADD datum_gewarnt_nicht_freigegeben DATE;
ALTER TABLE gesuch
	ADD datum_gewarnt_fehlende_quittung DATE;

ALTER TABLE gesuch_aud
	ADD datum_gewarnt_nicht_freigegeben DATE;
ALTER TABLE gesuch_aud
	ADD datum_gewarnt_fehlende_quittung DATE;