ALTER TABLE gesuch
	ADD dokumente_hochgeladen BIT NOT NULL DEFAULT FALSE;
ALTER TABLE gesuch_aud
	ADD dokumente_hochgeladen BIT;

UPDATE gesuch
SET dokumente_hochgeladen = TRUE
WHERE status = 'ERSTE_MAHNUNG_DOKUMENTE_HOCHGELADEN';
UPDATE gesuch
SET dokumente_hochgeladen = TRUE
WHERE status = 'ZWEITE_MAHNUNG_DOKUMENTE_HOCHGELADEN';
UPDATE gesuch
SET dokumente_hochgeladen = TRUE
WHERE status = 'NUR_SCHULAMT_DOKUMENTE_HOCHGELADEN';

UPDATE gesuch
SET status = 'ERSTE_MAHNUNG'
WHERE status = 'ERSTE_MAHNUNG_DOKUMENTE_HOCHGELADEN';
UPDATE gesuch
SET status = 'ZWEITE_MAHNUNG'
WHERE status = 'ZWEITE_MAHNUNG_DOKUMENTE_HOCHGELADEN';
UPDATE gesuch
SET status = 'NUR_SCHULAMT'
WHERE status = 'NUR_SCHULAMT_DOKUMENTE_HOCHGELADEN';

UPDATE antrag_status_history
SET status = 'ERSTE_MAHNUNG'
WHERE status = 'ERSTE_MAHNUNG_DOKUMENTE_HOCHGELADEN';
UPDATE antrag_status_history
SET status = 'ZWEITE_MAHNUNG'
WHERE status = 'ZWEITE_MAHNUNG_DOKUMENTE_HOCHGELADEN';
UPDATE antrag_status_history
SET status = 'NUR_SCHULAMT'
WHERE status = 'NUR_SCHULAMT_DOKUMENTE_HOCHGELADEN';