ALTER TABLE abwesenheit MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE abwesenheit_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE abwesenheit_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE abwesenheit_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE adresse MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE adresse_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE antrag_status_history MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE antrag_status_history_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE application_property MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE application_property_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE authorisierter_benutzer MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE belegung_ferieninsel MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE belegung_ferieninsel_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE belegung_ferieninsel_tag MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE belegung_ferieninsel_tag_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE belegung_tagesschule MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE belegung_tagesschule_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE benutzer MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE benutzer_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE betreuung MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE betreuung_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE betreuungsmitteilung_pensum MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE betreuungsmitteilung_pensum_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE betreuungspensum MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE betreuungspensum_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE betreuungspensum_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE betreuungspensum_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE dokument MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE dokument_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE dokument_grund MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE dokument_grund_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE download_file MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE ebegu_vorlage MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE ebegu_vorlage_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE einkommensverschlechterung MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE einkommensverschlechterung_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE einkommensverschlechterung_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE einkommensverschlechterung_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE einkommensverschlechterung_info MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE einkommensverschlechterung_info_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE einkommensverschlechterung_info_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE einkommensverschlechterung_info_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE erwerbspensum MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE erwerbspensum_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE erwerbspensum_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE erwerbspensum_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE fachstelle MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE fachstelle_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE fall MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE fall_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE familiensituation MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE familiensituation_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE familiensituation_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE familiensituation_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE ferieninsel_stammdaten MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE ferieninsel_stammdaten_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE ferieninsel_zeitraum MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE ferieninsel_zeitraum_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE finanzielle_situation MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE finanzielle_situation_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE finanzielle_situation_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE finanzielle_situation_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE generated_dokument MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE generated_dokument_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE gesuch MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE gesuch_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE gesuchsperiode MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE gesuchsperiode_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE gesuchsteller MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE gesuchsteller_adresse_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE gesuchsteller_adresse_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE gesuchsteller_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE gesuchsteller_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE gesuchsteller_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE institution MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE institution_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE institution_stammdaten MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE institution_stammdaten_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE institution_stammdaten_ferieninsel MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE institution_stammdaten_ferieninsel_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE institution_stammdaten_tagesschule MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE institution_stammdaten_tagesschule_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE kind MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE kind_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE kind_container MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE kind_container_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE mahnung MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE mahnung_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE mandant MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE mandant_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE mitteilung MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE mitteilung_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE modul_tagesschule MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE modul_tagesschule_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE pain001dokument MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE pain001dokument_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE pensum_fachstelle MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE pensum_fachstelle_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE sequence MODIFY user_mutiert VARCHAR(255);
ALTER TABLE traegerschaft MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE traegerschaft_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE verfuegung MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE verfuegung_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE verfuegung_zeitabschnitt MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE verfuegung_zeitabschnitt_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE vorlage MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE vorlage_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE wizard_step MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE wizard_step_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE workjob MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE zahlung MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE zahlung_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE zahlungsauftrag MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE zahlungsauftrag_aud MODIFY user_mutiert VARCHAR(255);
ALTER TABLE zahlungsposition MODIFY user_mutiert VARCHAR(255) NOT NULL;
ALTER TABLE zahlungsposition_aud MODIFY user_mutiert VARCHAR(255);