package ch.dvbern.ebegu.enums;

/**
 * Enum fuer den Status Events vom Gesuch.
 */
public enum AntragEvents {
	FREIGEBEN_SCHULAMT,
	FREIGABEQUITTUNG_ERSTELLEN,
	FREIGEBEN,
	ERSTES_OEFFNEN_JA,
	MAHNEN, GEPRUEFT,
	ZUWEISUNG_SCHULAMT,
	VERFUEGUNG_STARTEN,
	VERFUEGEN_OHNE_ANGEBOT,
	VERFUEGEN,
	BESCHWEREN,
	PRUEFEN_STV,
	DOKUMENT_HOCHLADEN,
	DOKUMENTE_GEPRUEFT,
	ZURUECK_NUR_SCHULAMT,
	ZURUECK_NUR_SCHULAMT_DOKUMENTE_HOCHGELADEN,
	ZURUECK_VERFUEGT,
	ZURUECK_KEIN_ANGEBOT,
	ZURUECK_PRUEFUNG_STV,
	ZURUECK_IN_BEARBEITUNG_STV,
	ZURUECK_GEPRUEFT_STV,
	ERSTES_OEFFNEN_STV,
	GEPRUEFT_STV,
	PRUEFUNG_ABGESCHLOSSEN,
	MAHNUNG_ABGELAUFEN,
	MAHNLAUF_BEENDEN
}
