package ch.dvbern.ebegu.enums;

/**
 * Enum fuer den Status vom Gesuch
 */
public enum AntragStatus {
	IN_BEARBEITUNG_GS,
	FREIGABEQUITTUNG,
	NUR_SCHULAMT,
	FREIGEGEBEN,
	IN_BEARBEITUNG_JA,
	ZURUECKGEWIESEN,
	ERSTE_MAHNUNG,
	ERSTE_MAHNUNG_ABGELAUFEN,
	ZWEITE_MAHNUNG,
	ZWEITE_MAHNUNG_ABGELAUFEN,
	GEPRUEFT,
	VERFUEGEN,
	VERFUEGT
}
