package ch.dvbern.ebegu.enums;

/**
 * Enum fuer das DTO JaxPendenzXX. Damit weisst man ob es sich um ein Gesuch oder eine Mutation handelt.
 */
public enum DokumentTyp {
	NACHWEIS_TRENNUNG,
	SORGERECHTSVEREINBARUNG,
	FACHSTELLENBEST_SOZ,
	FACHSTELLENBEST_BEH,
	NACHWEIS_ERWERBSPENSUM,
	NACHWEIS_SELBSTÄNDIGKEIT,
	NACHWEIS_AUSBILDUNG,
	NACHWEIS_RAV,
	BESTÄTIGUNG_ARZT,
	NACHWEIS_UNREG_ARBEITSZ,
	NACHWEIS_LANG_ARBEITSWEG,
	NACHWEIS_SONSTIGEN_ZUSCHLAG,
	NACHWEIS_GLEICHE_ARBEITSTAGE_BEI_TEILZEIT,
	NACHWEIS_FIXE_ARBEITSZEITEN,
	STEUERVERANLAGUNG,
	STEUERERKLAERUNG,
	JAHRESLOHNAUSWEISE,
	NACHWEIS_FAMILIENZULAGEN,
	NACHWEIS_ERSATZEINKOMMEN,
	NACHWEIS_ERHALTENE_ALIMENTE,
	NACHWEIS_GELEISTETE_ALIMENTE,
	NACHWEIS_VERMOEGEN,
	NACHWEIS_SCHULDEN,
	ERFOLGSRECHNUNGEN,
	UNTERSTÜTZUNGSNACHWEIS,
	//EKV
	NACHWEIS_EINKOMMENSSITUATION_MONAT,
	DIV
}
