package ch.dvbern.ebegu.enums;

/**
 * Enum fuer den Dokumenten Typ
 */
public enum DokumentTyp {
	NACHWEIS_TRENNUNG, //mutation
	FACHSTELLENBEST_SOZ,
	FACHSTELLENBEST_BEH,
	NACHWEIS_ERWERBSPENSUM,
	NACHWEIS_SELBSTAENDIGKEIT,
	NACHWEIS_AUSBILDUNG,
	NACHWEIS_RAV,
	BESTAETIGUNG_ARZT,
	NACHWEIS_UNREG_ARBEITSZ,
	NACHWEIS_LANG_ARBEITSWEG,
	NACHWEIS_SONSTIGEN_ZUSCHLAG,
	NACHWEIS_GLEICHE_ARBEITSTAGE_BEI_TEILZEIT,
	NACHWEIS_FIXE_ARBEITSZEITEN,
	STEUERVERANLAGUNG,
	STEUERERKLAERUNG,
	JAHRESLOHNAUSWEISE,
	NACHWEIS_FAMILIENZULAGEN,
	NACHWEIS_ERSATZEINKOMMEN,
	NACHWEIS_ERHALTENE_ALIMENTE,
	NACHWEIS_GELEISTETE_ALIMENTE,
	NACHWEIS_VERMOEGEN,
	NACHWEIS_SCHULDEN,
	ERFOLGSRECHNUNGEN_JAHR,
	ERFOLGSRECHNUNGEN_JAHR_MINUS1,
	ERFOLGSRECHNUNGEN_JAHR_MINUS2,
	//EKV
	NACHWEIS_EINKOMMENSSITUATION_MONAT,
	DIV,
	ORIGINAL_PAPIERGESUCH
}
