package ch.dvbern.ebegu.enums;

import ch.dvbern.ebegu.rules.RuleKey;


/**
 * Dieses Enum dient der Verwaltung von Server Seitigen Uebersetzbaren Messages. Die hier definierten keys sollten im
 * server-messages.properties file uebersetzt werden. Die Optionale Verklinkung mit anderen Enums ist rein informativ
 */
public enum MsgKey {


	ERWERBSPENSUM_GS1_MSG(RuleKey.ERWERBSPENSUM),
	ERWERBSPENSUM_GS2_MSG(RuleKey.ERWERBSPENSUM),
	ERWERBSPENSUM_ZUSCHLAG_GS1_MSG(RuleKey.ERWERBSPENSUM),
	ERWERBSPENSUM_ZUSCHLAG_GS2_MSG(RuleKey.ERWERBSPENSUM),
	ERWERBSPENSUM_ANSPRUCH(RuleKey.ERWERBSPENSUM),
	ERWERBSPENSUM_MAX_ZUSCHLAG(RuleKey.ERWERBSPENSUM),
	BETREUUNGSANGEBOT_MSG(RuleKey.BETREUUNGSANGEBOT_TYP),
	EINKOMMEN_MSG(RuleKey.EINKOMMEN),
	EINKOMMEN_VOLLKOSTEN_MSG(RuleKey.EINKOMMEN),
	EINKOMMENSVERSCHLECHTERUNG_ACCEPT_MSG(RuleKey.EINKOMMEN),
	EINKOMMENSVERSCHLECHTERUNG_NOT_ACCEPT_MSG(RuleKey.EINKOMMEN),

	MINDESTALTER_MSG(RuleKey.MINDESTALTER),

	ABWESENHEIT_MSG(RuleKey.ABWESENHEIT),

	WOHNHAFT_MSG(RuleKey.WOHNHAFT_IM_GLEICHEN_HAUSHALT),
	WOHNSITZ_MSG(RuleKey.WOHNSITZ),
	FACHSTELLE_MSG(RuleKey.FACHSTELLE),
	EINREICHUNGSFRIST_MSG(RuleKey.EINREICHUNGSFRIST),
	EINREICHUNGSFRIST_VOLLKOSTEN_MSG(RuleKey.EINREICHUNGSFRIST),
	RESTANSPRUCH_MSG(RuleKey.RESTANSPRUCH),
	REDUCKTION_RUECKWIRKEND_MSG(RuleKey.ANSPRUCHSBERECHNUNGSREGELN_MUTATIONEN),
	ANSPRUCHSAENDERUNG_MSG(RuleKey.ANSPRUCHSBERECHNUNGSREGELN_MUTATIONEN),

	GEKUENDIGT_VOR_EINTRITT_MSG(RuleKey.GEKUENDIGT_VOR_EINTRITT),
	FAMILIENSITUATION_HEIRAT_MSG(RuleKey.ZIVILSTANDSAENDERUNG),
	FAMILIENSITUATION_TRENNUNG_MSG(RuleKey.ZIVILSTANDSAENDERUNG);


	private RuleKey referencedRuleKey;

	MsgKey(RuleKey referecedRule) {
		this.referencedRuleKey = referecedRule;
	}

	MsgKey() {
	}

	public RuleKey getReferencedRuleKey() {
		return referencedRuleKey;
	}

	public void setReferencedRuleKey(RuleKey referencedRuleKey) {
		this.referencedRuleKey = referencedRuleKey;
	}
}
