package ch.dvbern.ebegu.enums;

public enum UserRole {
	ADMIN,
	SACHBEARBEITER_JA,
	SACHBEARBEITER_INSTITUTION,
	SACHBEARBEITER_TRAEGERSCHAFT,
	GESUCHSTELLER,
	JURIST,
	REVISOR,
	STEUERAMT,
	SCHULAMT
}
