package ch.dvbern.ebegu.enums;


public interface UserRoleName {

	String SUPER_ADMIN = "SUPER_ADMIN";
	String ADMIN = "ADMIN";
	String SACHBEARBEITER_JA = "SACHBEARBEITER_JA";
	String SACHBEARBEITER_INSTITUTION = "SACHBEARBEITER_INSTITUTION";
	String SACHBEARBEITER_TRAEGERSCHAFT = "SACHBEARBEITER_TRAEGERSCHAFT";
	String GESUCHSTELLER = "GESUCHSTELLER";
	String JURIST = "JURIST";
	String REVISOR = "REVISOR";
	String STEUERAMT = "STEUERAMT";
	String SCHULAMT = "SCHULAMT";


}
