package ch.dvbern.ebegu.enums;

/**
 * Enum fuer die Namen des WizardSteps
 */
public enum WizardStepName {
	GESUCH_ERSTELLEN,
	FAMILIENSITUATION,
	GESUCHSTELLER,
	UMZUG,
	KINDER,
	BETREUUNG,
	ABWESENHEIT,
	ERWERBSPENSUM,
	FINANZIELLE_SITUATION,
	EINKOMMENSVERSCHLECHTERUNG,
	DOKUMENTE,
	VERFUEGEN
}
