export enum TSBetreuungsstatus {
    AUSSTEHEND = <any> 'AUSSTEHEND',
    WARTEN = <any> 'WARTEN',
    SCHULAMT = <any> 'SCHULAMT',
    ABGEWIESEN = <any> 'ABGEWIESEN',
    NICHT_EINGETRETEN = <any> 'NICHT_EINGETRETEN',
    STORNIERT = <any> 'STORNIERT',
    BESTAETIGT = <any> 'BESTAETIGT',
    VERFUEGT = <any> 'VERFUEGT',
    GESCHLOSSEN_OHNE_VERFUEGUNG  = <any> 'GESCHLOSSEN_OHNE_VERFUEGUNG'
}
