/*
 * Ki-Tax: System for the management of external childcare subsidies
 * Copyright (C) 2017 City of Bern Switzerland
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

export enum TSDokumentTyp {

    NACHWEIS_TRENNUNG = <any> 'NACHWEIS_TRENNUNG',
    FACHSTELLENBEST_SOZ = <any> 'FACHSTELLENBEST_SOZ',
    FACHSTELLENBEST_BEH = <any> 'FACHSTELLENBEST_BEH',
    NACHWEIS_ERWERBSPENSUM = <any> 'NACHWEIS_ERWERBSPENSUM',
    NACHWEIS_SELBSTAENDIGKEIT = <any> 'NACHWEIS_SELBSTAENDIGKEIT',
    NACHWEIS_AUSBILDUNG = <any> 'NACHWEIS_AUSBILDUNG',
    NACHWEIS_RAV = <any> 'NACHWEIS_RAV',
    BESTAETIGUNG_ARZT = <any> 'BESTAETIGUNG_ARZT',
    NACHWEIS_UNREG_ARBEITSZ = <any> 'NACHWEIS_UNREG_ARBEITSZ',
    NACHWEIS_LANG_ARBEITSWEG = <any> 'NACHWEIS_LANG_ARBEITSWEG',
    NACHWEIS_SONSTIGEN_ZUSCHLAG = <any> 'NACHWEIS_SONSTIGEN_ZUSCHLAG',
    NACHWEIS_GLEICHE_ARBEITSTAGE_BEI_TEILZEIT = <any> 'NACHWEIS_GLEICHE_ARBEITSTAGE_BEI_TEILZEIT',
    NACHWEIS_FIXE_ARBEITSZEITEN = <any> 'NACHWEIS_FIXE_ARBEITSZEITEN',
    STEUERVERANLAGUNG = <any> 'STEUERVERANLAGUNG',
    STEUERERKLAERUNG = <any> 'STEUERERKLAERUNG',
    JAHRESLOHNAUSWEISE = <any> 'JAHRESLOHNAUSWEISE',
    NACHWEIS_FAMILIENZULAGEN = <any> 'NACHWEIS_FAMILIENZULAGEN',
    NACHWEIS_ERSATZEINKOMMEN = <any> 'NACHWEIS_ERSATZEINKOMMEN',
    NACHWEIS_ERHALTENE_ALIMENTE = <any> 'NACHWEIS_ERHALTENE_ALIMENTE',
    NACHWEIS_GELEISTETE_ALIMENTE = <any> 'NACHWEIS_GELEISTETE_ALIMENTE',
    NACHWEIS_VERMOEGEN = <any> 'NACHWEIS_VERMOEGEN',
    NACHWEIS_SCHULDEN = <any> 'NACHWEIS_SCHULDEN',
    ERFOLGSRECHNUNGEN_JAHR = <any> 'ERFOLGSRECHNUNGEN_JAHR',
    ERFOLGSRECHNUNGEN_JAHR_MINUS1 = <any> 'ERFOLGSRECHNUNGEN_JAHR_MINUS1',
    ERFOLGSRECHNUNGEN_JAHR_MINUS2 = <any> 'ERFOLGSRECHNUNGEN_JAHR_MINUS2',
    NACHWEIS_EINKOMMENSSITUATION_MONAT = <any> 'NACHWEIS_EINKOMMENSSITUATION_MONAT',
    DIV = <any> 'DIV',
    ORIGINAL_PAPIERGESUCH = <any> 'ORIGINAL_PAPIERGESUCH',
    UNTERSTUETZUNGSBESTAETIGUNG = <any> 'UNTERSTUETZUNGSBESTAETIGUNG'
}

export function getTSTSDokumentTypValues(): Array<TSDokumentTyp> {
    return [

        TSDokumentTyp.NACHWEIS_TRENNUNG,
        TSDokumentTyp.FACHSTELLENBEST_SOZ,
        TSDokumentTyp.FACHSTELLENBEST_BEH,
        TSDokumentTyp.NACHWEIS_ERWERBSPENSUM,
        TSDokumentTyp.NACHWEIS_SELBSTAENDIGKEIT,
        TSDokumentTyp.NACHWEIS_AUSBILDUNG,
        TSDokumentTyp.NACHWEIS_RAV,
        TSDokumentTyp.BESTAETIGUNG_ARZT,
        TSDokumentTyp.NACHWEIS_UNREG_ARBEITSZ,
        TSDokumentTyp.NACHWEIS_LANG_ARBEITSWEG,
        TSDokumentTyp.NACHWEIS_SONSTIGEN_ZUSCHLAG,
        TSDokumentTyp.NACHWEIS_GLEICHE_ARBEITSTAGE_BEI_TEILZEIT,
        TSDokumentTyp.NACHWEIS_FIXE_ARBEITSZEITEN,
        TSDokumentTyp.STEUERVERANLAGUNG,
        TSDokumentTyp.STEUERERKLAERUNG,
        TSDokumentTyp.JAHRESLOHNAUSWEISE,
        TSDokumentTyp.NACHWEIS_FAMILIENZULAGEN,
        TSDokumentTyp.NACHWEIS_ERSATZEINKOMMEN,
        TSDokumentTyp.NACHWEIS_ERHALTENE_ALIMENTE,
        TSDokumentTyp.NACHWEIS_GELEISTETE_ALIMENTE,
        TSDokumentTyp.NACHWEIS_VERMOEGEN,
        TSDokumentTyp.NACHWEIS_SCHULDEN,
        TSDokumentTyp.ERFOLGSRECHNUNGEN_JAHR,
        TSDokumentTyp.ERFOLGSRECHNUNGEN_JAHR_MINUS1,
        TSDokumentTyp.ERFOLGSRECHNUNGEN_JAHR_MINUS2,
        TSDokumentTyp.NACHWEIS_EINKOMMENSSITUATION_MONAT,
        TSDokumentTyp.DIV,
        TSDokumentTyp.ORIGINAL_PAPIERGESUCH,
        TSDokumentTyp.UNTERSTUETZUNGSBESTAETIGUNG
    ];
}
