export enum TSGeneratedDokumentTyp {
    VERFUEGUNG = <any>'VERFUEGUNG',
    FINANZIELLE_SITUATION = <any>'FINANZIELLE_SITUATION',
    BEGLEITSCHREIBEN = <any>'BEGLEITSCHREIBEN',
    MAHNUNG = <any>'MAHNUNG',
    NICHTEINTRETEN = <any>'NICHTEINTRETEN'
}
