export enum TSMitteilungEvent {
    MUTATIONSMITTEILUNG_NEUE_MUTATION = <any> 'MUTATIONSMITTEILUNG_NEUE_MUTATION',
    MUTATIONSMITTEILUNG_MUTATION_REMOVED = <any> 'MUTATIONSMITTEILUNG_MUTATION_REMOVED',
}
