export enum TSModulname {
    VORMITTAG = <any> 'VORMITTAG',
    MITTAG = <any> 'MITTAG',
    MITTAG_HALB = <any> 'MITTAG_HALB',
    NACHMITTAGS_1 = <any> 'NACHMITTAGS_1',
    NACHMITTAGS_1_HALB = <any> 'NACHMITTAGS_1_HALB',
    NACHMITTAGS_2 = <any> 'NACHMITTAGS_2',
    NACHMITTAGS_2_HALB = <any> 'NACHMITTAGS_2_HALB'
}
